In [1]:
import pymysql
import pandas as pd
import requests
from tqdm import tqdm
tqdm.pandas()
import pandas as pd
import random
import time
import numpy as np
from sqlalchemy import create_engine, text
api_key='WpHBwNY0OhnyduM02i3Ca2xD9Wv63uI7eHA0imZ2'
nickname='sdkk003'
header={'accept': 'application/json','x-api-key': api_key}
username=f'https://open-api.bser.io/v1/user/nickname?query={nickname}'
userinfo=requests.get(username,headers=header).json()
userdf=pd.DataFrame(userinfo)
userNum=userdf.user.userNum
user_url=f'https://open-api.bser.io/v1/user/games/{userNum}'
res = requests.get(user_url, headers=header).json()
df=pd.DataFrame(res)
gamedata=df.userGames
gamedf=pd.DataFrame(gamedata)
games=gamedf.userGames[0]
gamesdata=gamedata.values
datas=[]
for i in range(len(gamesdata)):
    datas.append(gamesdata[i].values())
gamedf=pd.DataFrame(datas,columns=gamesdata[3].keys())
time.sleep(1)   
gamedatalist=[]
for j in tqdm(range(len(gamedf.gameId))):
    user_url=f'https://open-api.bser.io/v1/games/{gamedf.gameId[j]}'
    gamedatalist.append(requests.get(user_url, headers=header).json())
    time.sleep(1)
gamelist=pd.DataFrame(gamedatalist)
gamelist=gamelist.userGames
engine = create_engine('mysql+pymysql://takealook:tmddk0908@localhost:3308/apidb')

100%|██████████| 10/10 [00:16<00:00,  1.64s/it]

In [27]:
rankdata=f'https://open-api.bser.io/v1/rank/top/27/3'
rankres=requests.get(rankdata,headers=header).json()
rankdf=pd.DataFrame(rankres)
rankuser=pd.DataFrame(rankdf.topRanks)
time.sleep(5)
for i in tqdm(range(len(rankuser.topRanks))):
    userNum=rankuser.topRanks[i]['userNum']
    user_url=f'https://open-api.bser.io/v1/user/games/{userNum}'
    res = requests.get(user_url, headers=header).json()
    df=pd.DataFrame(res)
    gamedata=df.userGames
    gamedf=pd.DataFrame(gamedata)
    games=gamedf.userGames[0]
    gamesdata=gamedata.values
    datas=[]
    for j in range(len(gamesdata)):
        datas.append(gamesdata[j].values())
    gamedf=pd.DataFrame(datas,columns=gamesdata[3].keys())
    time.sleep(1)   

    insert=[]
    for i in range(len(gamedf)):
        insertdf=[]
        insertdf.append(gamedf.gameId[i])
        insertdf.append(gamedf.nickname[i])
        insertdf.append(gamedf.mmrAfter[i])
        insertdf.append(gamedf.matchingMode[i])
        insertdf.append(gamedf.seasonId[i])
        insertdf.append(gamedf.skinCode[i])
        insertdf.append(gamedf.characterLevel[i])
        insertdf.append(gamedf.playerKill[i])
        insertdf.append(gamedf.playerAssistant[i])
        insertdf.append(gamedf.equipment[i]['0'])
        insertdf.append(gamedf.equipment[i]['1'])
        insertdf.append(gamedf.equipment[i]['2'])
        insertdf.append(gamedf.equipment[i]['3'])
        insertdf.append(gamedf.equipment[i]['4'])
        insertdf.append(gamedf.serverName[i])
        insertdf.append(gamedf.teamNumber[i])
        insertdf.append(gamedf.victory[i])
        insertdf.append(gamedf.giveUp[i])
        insertdf.append(gamedf.killer[i])
        insertdf.append(gamedf.killerCharacter[i])
        insertdf.append(gamedf.routeIdOfStart[i])
        insert.append(insertdf)
    column=['gameId','userNum','nickname','mmrAfter','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
    rdatadf=pd.DataFrame(insert,columns=column)
    runiquedf = rdatadf.drop_duplicates(subset=['gameId', 'userNum'])
    insert.to_sql('e_data', con=engine, if_exists='append', index=False)
    time.sleep(30)

  0%|          | 0/1001 [00:01<?, ?it/s]

NameError: name 'timesleep' is not defined

In [23]:
insert=[]
for i in range(len(gamedf)):
    insertdf=[]
    insertdf.append(gamedf.gameId[i])
    insertdf.append(gamedf.nickname[i])
    insertdf.append(gamedf.mmrAfter[i])
    insertdf.append(gamedf.matchingMode[i])
    insertdf.append(gamedf.seasonId[i])
    insertdf.append(gamedf.skinCode[i])
    insertdf.append(gamedf.characterLevel[i])
    insertdf.append(gamedf.playerKill[i])
    insertdf.append(gamedf.playerAssistant[i])
    insertdf.append(gamedf.equipment[i]['0'])
    insertdf.append(gamedf.equipment[i]['1'])
    insertdf.append(gamedf.equipment[i]['2'])
    insertdf.append(gamedf.equipment[i]['3'])
    insertdf.append(gamedf.equipment[i]['4'])
    # insertdf.append(gamedf.skillLevelInfo)
    insertdf.append(gamedf.serverName[i])
    insertdf.append(gamedf.teamNumber[i])
    insertdf.append(gamedf.victory[i])
    insertdf.append(gamedf.giveUp[i])
    insertdf.append(gamedf.killer[i])
    insertdf.append(gamedf.killerCharacter[i])
    insertdf.append(gamedf.routeIdOfStart[i])
    insert.append(insertdf)
column=['gameId','nickname','mmrAfter','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
insert=pd.DataFrame(insert,columns=column)

In [29]:
insert

,gameId,nickname,mmrAfter,matchingMode,seasonId,skinCode,characterLevel,playerKill,playerAssistant,equipment1,...,equipment3,equipment4,equipment5,serverName,teamNumber,victory,giveUp,killer,killerCharacter,routeIdOfStart
0,39967895,손이짧아슬픈로지,9463,3,27,1021000,13,3,0,116405,...,201414,203405,204509,Asia,1,0,0,player,Nadine,49944
1,39966322,손이짧아슬픈로지,9538,3,27,1021000,20,6,3,116503,...,201411,203502,204509,Asia,1,0,0,player,Hyunwoo,49944
2,39965020,손이짧아슬픈로지,9518,3,27,1021000,20,9,6,116503,...,201408,203502,204509,Asia,1,1,0,player,Garnet,49944
3,39963808,손이짧아슬픈로지,9398,3,27,1021000,20,4,4,116503,...,201408,203502,204509,Asia,1,0,0,player,Zahir,49944
4,39961406,손이짧아슬픈로지,9441,3,27,1021000,20,5,1,116503,...,201414,203502,204509,Asia,1,0,0,player,Garnet,49944
5,39960627,손이짧아슬픈로지,9484,3,27,1006000,20,6,3,115701,...,201506,203502,204504,Asia,1,1,0,player,Darko,0
6,39960209,손이짧아슬픈로지,9445,3,27,1024003,16,5,0,120501,...,201503,203403,204304,Asia,1,0,0,player,Chloe,0
7,39959469,손이짧아슬픈로지,9494,3,27,1006000,20,10,3,115501,...,201701,203502,204504,Asia,1,0,0,player,Darko,0
8,39958639,손이짧아슬픈로지,9452,3,27,1072000,20,7,3,118701,...,201411,203502,204509,Asia,1,0,0,player,Magnus,0
9,39957978,손이짧아슬픈로지,9433,3,27,1072000,20,8,3,118404,...,201408,203502,204504,Asia,1,0,0,player,Leon,0

In [33]:
insert.to_sql('e_data', con=engine, if_exists='append', index=False)

10

In [46]:
gamedf=gamedf.rename(columns={'isLeavingBeforeCreditRevivalTerminate':'isLeavingBeforeCreditRevivalTerminateB'})

In [26]:
# MySQL 연결 엔진 생성
insert.to_sql('e_data', con=engine, if_exists='replace', index=False)

10

In [31]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM e_data"))
    
    # 조회 결과 출력
    for row in result:
        print(row)

(40045297, 'sdkk003', 4636, 3, 27, 1030003, 19, 3, 5, 104502, 202522, 201415, 203505, 204501, 'Asia', 5.0, 0, 0, 'player', 'Arda', 1241)
(39907701, 'sdkk003', 1268, 2, 0, 1008002, 20, 5, 4, 121405, 202510, 201506, 203502, 204504, 'Asia', 20.0, 6, -1, 'Nadine', '역마', 21)
(39907562, 'sdkk003', 337, 2, 0, 1008002, 9, 1, 2, 121404, 202405, 201417, 203405, 204408, 'Asia', 20.0, 5, -1, 'Aiden', '0', 24)
(39907335, 'sdkk003', 4611, 3, 27, 1008002, 15, 2, 3, 121404, 202405, 201417, 203502, 204504, 'Asia', 2.0, 0, 0, 'player', 'Chiara', 10681)
(39906967, 'sdkk003', 4632, 3, 27, 1008002, 20, 5, 7, 121404, 202510, 201506, 203502, 204504, 'Asia', 2.0, 0, 0, 'player', 'Hyejin', 10681)
(39906482, 'sdkk003', 4564, 3, 27, 1008002, 20, 1, 8, 121701, 202510, 201506, 203502, 204504, 'Asia', 2.0, 1, 0, 'player', 'LiDailin', 10681)
(39906231, 'sdkk003', 4440, 3, 27, 1008002, 12, 3, 4, 121404, 202510, 201417, 203502, 204504, 'Asia', 3.0, 0, 0, 'player', 'Isaac', 10681)
(39905642, 'sdkk003', 4458, 3, 27, 1008002, 20, 7, 4, 121404, 202510, 201417, 203502, 204504, 'Asia', 3.0, 0, 0, 'player', 'Laura', 10681)
(39904950, 'sdkk003', 4356, 3, 27, 1008002, 20, 7, 7, 121404, 202510, 201506, 203502, 204504, 'Asia', 5.0, 0, 0, 'player', 'Rio', 10681)
(39904425, 'sdkk003', 4237, 3, 27, 1008002, 18, 2, 4, 121404, 202510, 201417, 203502, 204408, 'Asia', 7.0, 0, 0, 'player', 'Garnet', 10681)
(39967895, '손이짧아슬픈로지', 9463, 3, 27, 1021000, 13, 3, 0, 116405, 202418, 201414, 203405, 204509, 'Asia', 1.0, 0, 0, 'player', 'Nadine', 49944)
(39966322, '손이짧아슬픈로지', 9538, 3, 27, 1021000, 20, 6, 3, 116503, 202510, 201411, 203502, 204509, 'Asia', 1.0, 0, 0, 'player', 'Hyunwoo', 49944)
(39965020, '손이짧아슬픈로지', 9518, 3, 27, 1021000, 20, 9, 6, 116503, 202510, 201408, 203502, 204509, 'Asia', 1.0, 1, 0, 'player', 'Garnet', 49944)
(39963808, '손이짧아슬픈로지', 9398, 3, 27, 1021000, 20, 4, 4, 116503, 202418, 201408, 203502, 204509, 'Asia', 1.0, 0, 0, 'player', 'Zahir', 49944)
(39961406, '손이짧아슬픈로지', 9441, 3, 27, 1021000, 20, 5, 1, 116503, 202510, 201414, 203502, 204509, 'Asia', 1.0, 0, 0, 'player', 'Garnet', 49944)
(39960627, '손이짧아슬픈로지', 9484, 3, 27, 1006000, 20, 6, 3, 115701, 202523, 201506, 203502, 204504, 'Asia', 1.0, 1, 0, 'player', 'Darko', 0)
(39960209, '손이짧아슬픈로지', 9445, 3, 27, 1024003, 16, 5, 0, 120501, 702602, 201503, 203403, 204304, 'Asia', 1.0, 0, 0, 'player', 'Chloe', 0)
(39959469, '손이짧아슬픈로지', 9494, 3, 27, 1006000, 20, 10, 3, 115501, 202523, 201701, 203502, 204504, 'Asia', 1.0, 0, 0, 'player', 'Darko', 0)
(39958639, '손이짧아슬픈로지', 9452, 3, 27, 1072000, 20, 7, 3, 118701, 202510, 201411, 203502, 204509, 'Asia', 1.0, 0, 0, 'player', 'Magnus', 0)
(39957978, '손이짧아슬픈로지', 9433, 3, 27, 1072000, 20, 8, 3, 118404, 202509, 201408, 203502, 204504, 'Asia', 1.0, 0, 0, 'player', 'Leon', 0)