In [1]:
import pymysql
import pandas as pd
import requests
from tqdm import tqdm
tqdm.pandas()
import pandas as pd
import random
import time
import numpy as np
from sqlalchemy import create_engine, text
api_key='WpHBwNY0OhnyduM02i3Ca2xD9Wv63uI7eHA0imZ2'
nickname='sdkk003'
header={'accept': 'application/json','x-api-key': api_key}
engine = create_engine('mysql+pymysql://takealook:tmddk0908@localhost:3308/apidb')

In [ ]:

userurl=f'https://open-api.bser.io/v1/user/nickname?query={username}'
userres=requests.get(userurl, headers=header).json()
userdf=pd.DataFrame(userres)
userNum=userdf.user.userNum
user_url=f'https://open-api.bser.io/v1/user/games/{userNum}'
usergameres = requests.get(user_url, headers=header).json()
usergamedf=pd.DataFrame(usergameres)
gamedata=usergamedf.userGames
gamelist=gamedata.values
gamedf=gamelist
# print(gamedf[0])
usergames=[]
for j in range(len(gamedf)):
    insertdf=[]
    insertdf.append(gamedf[j]['gameId']) 
    insertdf.append(gamedf[j]['userNum']) 
    insertdf.append(gamedf[j]['nickname'])
    # insertdf.append(gamedf[j][0]['mmr'])
    insertdf.append(gamedf[j]['matchingMode'])
    insertdf.append(gamedf[j]['seasonId'])
    insertdf.append(gamedf[j]['skinCode'])
    insertdf.append(gamedf[j]['characterLevel'])
    insertdf.append(gamedf[j]['playerKill'])
    insertdf.append(gamedf[j]['playerAssistant'])
    try:insertdf.append(gamedf[j]['equipment']['0'])
    except:insertdf.append(0)
    try:insertdf.append(gamedf[j]['equipment']['1'])
    except:insertdf.append(0)
    try:insertdf.append(gamedf[j]['equipment']['2'])
    except:insertdf.append("none")
    try:insertdf.append(gamedf[j]['equipment']['3'])
    except:insertdf.append("none")
    try:insertdf.append(gamedf[j]['equipment']['4'])
    except:insertdf.append("none")
    insertdf.append(gamedf[j]['serverName'])
    insertdf.append(gamedf[j]['teamNumber'])
    insertdf.append(gamedf[j]['victory'])
    insertdf.append(gamedf[j]['giveUp'])
    insertdf.append(gamedf[j]['killer'])
    try:
        insertdf.append(gamedf[j]['killerCharacter'])
    except:
        insertdf.append("none")
    insertdf.append(gamedf[j]['routeIdOfStart'])
    usergames.append(insertdf)
    column=['gameId','userNum','nickname','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
    rdatadf=pd.DataFrame(usergames,columns=column)
    runiquedf = rdatadf.drop_duplicates(subset=['gameId', 'userNum'])

In [18]:
rdatadf

,gameId,userNum,nickname,matchingMode,seasonId,skinCode,characterLevel,playerKill,playerAssistant,equipment1,...,equipment3,equipment4,equipment5,serverName,teamNumber,victory,giveUp,killer,killerCharacter,routeIdOfStart
0,41578124,4969807,손이짧아슬픈로지,3,27,1058004,20,8,8,117702,...,201504,203510,204502,Asia,2,0,0,player,Tsubame,5823

In [20]:
#유저 데이터 조회루트
nickname='손이짧아슬픈로지'
username=f'https://open-api.bser.io/v1/user/nickname?query={nickname}'
userinfo=requests.get(username,headers=header).json()
userdf=pd.DataFrame(userinfo)
userNum=userdf.user.userNum
user_url=f'https://open-api.bser.io/v1/user/games/{userNum}'
res = requests.get(user_url, headers=header).json()
df=pd.DataFrame(res)
next=df['next'][0]
gamedata=df.userGames
gamedata=pd.DataFrame(df.userGames)
gamesdata=gamedata.values
gamedf=gamesdata
finalgamedf=[]
for j in range(len(gamedf)):
    insertdf=[]
    insertdf.append(gamedf[j][0]['gameId']) 
    insertdf.append(gamedf[j][0]['userNum']) 
    insertdf.append(gamedf[j][0]['nickname'])
    # insertdf.append(gamedf[j][0]['mmr'])
    insertdf.append(gamedf[j][0]['matchingMode'])
    insertdf.append(gamedf[j][0]['seasonId'])
    insertdf.append(gamedf[j][0]['skinCode'])
    insertdf.append(gamedf[j][0]['characterLevel'])
    insertdf.append(gamedf[j][0]['playerKill'])
    insertdf.append(gamedf[j][0]['playerAssistant'])
    try:insertdf.append(gamedf[j][0]['equipment']['0'])
    except:insertdf.append(0)
    try:insertdf.append(gamedf[j][0]['equipment']['1'])
    except:insertdf.append(0)
    try:insertdf.append(gamedf[j][0]['equipment']['2'])
    except:insertdf.append("none")
    try:insertdf.append(gamedf[j][0]['equipment']['3'])
    except:insertdf.append("none")
    try:insertdf.append(gamedf[j][0]['equipment']['4'])
    except:insertdf.append("none")
    insertdf.append(gamedf[j][0]['serverName'])
    insertdf.append(gamedf[j][0]['teamNumber'])
    insertdf.append(gamedf[j][0]['victory'])
    insertdf.append(gamedf[j][0]['giveUp'])
    insertdf.append(gamedf[j][0]['killer'])
    try:
        insertdf.append(gamedf[j][0]['killerCharacter'])
    except:
        insertdf.append("none")
    insertdf.append(gamedf[j][0]['routeIdOfStart'])
    finalgamedf.append(insertdf)
    column=['gameId','userNum','nickname','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
    rdatadf=pd.DataFrame(finalgamedf,columns=column)
    runiquedf = rdatadf.drop_duplicates(subset=['gameId', 'userNum'])
user_url=f'https://open-api.bser.io/v1/user/games/4969807?next={next}'
res = requests.get(user_url, headers=header).json()
df=pd.DataFrame(res)
gamedata=df.userGames
gamedf=pd.DataFrame(gamedata)
games=gamedf.userGames[0]
gamesdata=gamedata.values
print("nextpage")

nextpage

In [3]:
rdatadf

,gameId,userNum,nickname,matchingMode,seasonId,skinCode,characterLevel,playerKill,playerAssistant,equipment1,...,equipment3,equipment4,equipment5,serverName,teamNumber,victory,giveUp,killer,killerCharacter,routeIdOfStart
0,41310155,4969807,손이짧아슬픈로지,3,27,1002002,19,2,1,116404,...,201503,203504,204410,Asia,1,0,0,player,Bernice,0
1,41308948,4969807,손이짧아슬픈로지,3,27,1021000,20,11,9,116503,...,201502,203502,204504,Asia,1,0,0,player,Bianca,0
2,41307400,4969807,손이짧아슬픈로지,3,27,1021000,20,10,8,116503,...,201502,205501,204509,Asia,2,1,0,player,Nadine,0
3,41306807,4969807,손이짧아슬픈로지,3,27,1021000,13,2,1,116405,...,201408,205501,204509,Asia,2,0,0,player,Nicky,49944
4,41306397,4969807,손이짧아슬픈로지,3,27,1021000,10,1,0,116405,...,201414,203405,204418,Asia,2,0,0,player,Sissela,49944
5,41301061,4969807,손이짧아슬픈로지,6,0,1024003,17,7,9,120702,...,201503,203510,204413,Asia,2,0,0,player,Shoichi,0
6,41300543,4969807,손이짧아슬픈로지,6,0,1035000,19,7,7,111702,...,201503,203504,204502,Asia,2,0,0,player,William,0
7,41295930,4969807,손이짧아슬픈로지,3,27,1058004,18,6,3,117702,...,201503,203507,204505,Asia,1,0,0,player,Magnus,5823
8,41295423,4969807,손이짧아슬픈로지,3,27,1006004,20,11,3,115501,...,201506,205501,204509,Asia,2,0,0,player,Alex,45735
9,41295146,4969807,손이짧아슬픈로지,3,27,1006004,16,4,0,115402,...,201506,205501,204504,Asia,2,0,0,player,Nadine,45735

In [ ]:
gamesdata[9][0].values()

In [ ]:
df.userGames[0]['userNum']

In [2]:
rankdata=f'https://open-api.bser.io/v1/rank/top/27/3'
rankres=requests.get(rankdata,headers=header).json()
rankdf=pd.DataFrame(rankres)
rankuser=pd.DataFrame(rankdf.topRanks)

In [ ]:
user_url=f'https://open-api.bser.io/v1/user/games/4969807'
res = requests.get(user_url, headers=header).json()
df=pd.DataFrame(res)
gamedata=df.userGames
gamedf=pd.DataFrame(gamedata)
games=gamedf.userGames[0]
gamesdata=gamedata.values
while res['userGames'][9]['seasonId']==27:
    next=res['next']
    print(next)
    datas=[]
    for i in range(len(gamesdata)):
        datas.append(gamesdata[i].values())
    gamedf=pd.DataFrame(datas,columns=gamesdata[9].keys())
    time.sleep(1)
    gamedatalist=[]
    for j in tqdm(range(len(gamedf.gameId))):
        user_url=f'https://open-api.bser.io/v1/games/{gamedf.gameId[j]}'
        gamedatalist.append(requests.get(user_url, headers=header).json())
        time.sleep(1)
    gamenext=pd.DataFrame(gamedatalist)
    gamelist=gamenext.userGames
    finalgamedf=[]
    j=0
    i=0
    print("makedf")
    for j in range(len(gamelist)):
        for i in range(len(gamelist[j])):
            insertdf=[]
            # print(j,i)
            insertdf.append(gamelist[j][i]['gameId']) 
            insertdf.append(gamelist[j][i]['userNum']) 
            insertdf.append(gamelist[j][i]['nickname'])
            insertdf.append(gamelist[j][i]['mmrAfter'])
            insertdf.append(gamelist[j][i]['matchingMode'])
            insertdf.append(gamelist[j][i]['seasonId'])
            insertdf.append(gamelist[j][i]['skinCode'])
            insertdf.append(gamelist[j][i]['characterLevel'])
            insertdf.append(gamelist[j][i]['playerKill'])
            insertdf.append(gamelist[j][i]['playerAssistant'])
            try:insertdf.append(gamelist[j][i]['equipment']['0'])
            except:insertdf.append(0)
            try:insertdf.append(gamelist[j][i]['equipment']['1'])
            except:insertdf.append(0)
            try:insertdf.append(gamelist[j][i]['equipment']['2'])
            except:insertdf.append("none")
            try:insertdf.append(gamelist[j][i]['equipment']['3'])
            except:insertdf.append("none")
            try:insertdf.append(gamelist[j][i]['equipment']['4'])
            except:insertdf.append("none")
            insertdf.append(gamelist[j][i]['serverName'])
            insertdf.append(gamelist[j][i]['teamNumber'])
            insertdf.append(gamelist[j][i]['victory'])
            insertdf.append(gamelist[j][i]['giveUp'])
            insertdf.append(gamelist[j][i]['killer'])
            try:
                insertdf.append(gamelist[j][i]['killerCharacter'])
            except:
                insertdf.append("none")
            insertdf.append(gamelist[j][i]['routeIdOfStart'])
            finalgamedf.append(insertdf)
        column=['gameId','userNum','nickname','mmrAfter','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
        rdatadf=pd.DataFrame(finalgamedf,columns=column)
        runiquedf = rdatadf.drop_duplicates(subset=['gameId', 'userNum'])
    #   runiquedf.to_sql('e_data', con=engine, if_exists='append', index=False)
    print("cycle1complet")
    time.sleep(5)
    user_url=f'https://open-api.bser.io/v1/user/games/4969807?next={next}'
    res = requests.get(user_url, headers=header).json()
    df=pd.DataFrame(res)
    gamedata=df.userGames
    gamedf=pd.DataFrame(gamedata)
    games=gamedf.userGames[0]
    gamesdata=gamedata.values
    print("nextpage")

In [ ]:
gamedatalist[7]['code']

In [30]:
# user_url=f'https://open-api.bser.io/v1/user/games/384037?next=37856269'
user_url=f'https://open-api.bser.io/v1/user/games/4969807'
nextdata = requests.get(user_url, headers=header).json()
nextdata=pd.DataFrame(res)

In [ ]:
res['next']

In [ ]:
nextdata.next

In [ ]:
finalgamedf=[]
for j in range(len(gamelist)):
    for i in range(len(gamelist[j])):
        insertdf=[]
        # print(j,i)
        insertdf.append(gamelist[j][i]['gameId']) 
        insertdf.append(gamelist[j][i]['userNum']) 
        insertdf.append(gamelist[j][i]['nickname'])
        insertdf.append(gamelist[j][i]['mmrAfter'])
        insertdf.append(gamelist[j][i]['matchingMode'])
        insertdf.append(gamelist[j][i]['seasonId'])
        insertdf.append(gamelist[j][i]['skinCode'])
        insertdf.append(gamelist[j][i]['characterLevel'])
        insertdf.append(gamelist[j][i]['playerKill'])
        insertdf.append(gamelist[j][i]['playerAssistant'])
        insertdf.append(gamelist[j][i]['equipment']['0'])
        insertdf.append(gamelist[j][i]['equipment']['1'])
        insertdf.append(gamelist[j][i]['equipment']['2'])
        insertdf.append(gamelist[j][i]['equipment']['3'])
        insertdf.append(gamelist[j][i]['equipment']['4'])
        insertdf.append(gamelist[j][i]['serverName'])
        insertdf.append(gamelist[j][i]['teamNumber'])
        insertdf.append(gamelist[j][i]['victory'])
        insertdf.append(gamelist[j][i]['giveUp'])
        insertdf.append(gamelist[j][i]['killer'])
        try:
            insertdf.append(gamelist[j][i]['killerCharacter'])
        except:
            insertdf.append("none")
        insertdf.append(gamelist[j][i]['routeIdOfStart'])
        finalgamedf.append(insertdf)
    column=['gameId','userNum','nickname','mmrAfter','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
    rdatadf=pd.DataFrame(finalgamedf,columns=column)
    runiquedf = rdatadf.drop_duplicates(subset=['gameId', 'userNum'])
    runiquedf.to_sql('e_data', con=engine, if_exists='append', index=False)
    # print(i)

In [ ]:
gamelist[0][1]['mmrBefore']

In [ ]:
for i in range(len(gamesdata)):
    for j in range(len(gamesdata)):
        if(len(gamesdata[i].keys())<len(gamesdata[j].keys())):
            max=j
print(max)

In [8]:
rankdata=f'https://open-api.bser.io/v1/rank/top/27/3'
rankres=requests.get(rankdata,headers=header).json()
rankdf=pd.DataFrame(rankres)
rankuser=pd.DataFrame(rankdf.topRanks)

In [ ]:
rankdata=f'https://open-api.bser.io/v1/rank/top/27/3'
rankres=requests.get(rankdata,headers=header).json()
rankdf=pd.DataFrame(rankres)
rankuser=pd.DataFrame(rankdf.topRanks)
time.sleep(5)
for i in tqdm(range(len(rankuser.topRanks))):
    userNum=rankuser.topRanks[i]['userNum']
    user_url=f'https://open-api.bser.io/v1/user/games/{userNum}'
    res = requests.get(user_url, headers=header).json()
    df=pd.DataFrame(res)
    gamedata=df.userGames
    gamedf=pd.DataFrame(gamedata)
    games=gamedf.userGames[0]
    gamesdata=gamedata.values
    datas=[]
    for j in range(len(gamesdata)):
        datas.append(gamesdata[j].values())
    gamedf=pd.DataFrame(datas,columns=gamesdata[3].keys())
    time.sleep(1)   

    insert=[]
    for i in range(len(gamedf)):
        insertdf=[]
        insertdf.append(gamedf.gameId[i])
        insertdf.append(gamedf.nickname[i])
        insertdf.append(gamedf.mmrAfter[i])
        insertdf.append(gamedf.matchingMode[i])
        insertdf.append(gamedf.seasonId[i])
        insertdf.append(gamedf.skinCode[i])
        insertdf.append(gamedf.characterLevel[i])
        insertdf.append(gamedf.playerKill[i])
        insertdf.append(gamedf.playerAssistant[i])
        insertdf.append(gamedf.equipment[i]['0'])
        insertdf.append(gamedf.equipment[i]['1'])
        insertdf.append(gamedf.equipment[i]['2'])
        insertdf.append(gamedf.equipment[i]['3'])
        insertdf.append(gamedf.equipment[i]['4'])
        insertdf.append(gamedf.serverName[i])
        insertdf.append(gamedf.teamNumber[i])
        insertdf.append(gamedf.victory[i])
        insertdf.append(gamedf.giveUp[i])
        insertdf.append(gamedf.killer[i])
        insertdf.append(gamedf.killerCharacter[i])
        insertdf.append(gamedf.routeIdOfStart[i])
        insert.append(insertdf)
    column=['gameId','userNum','nickname','mmrAfter','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
    rdatadf=pd.DataFrame(insert,columns=column)
    runiquedf = rdatadf.drop_duplicates(subset=['gameId', 'userNum'])
    insert.to_sql('e_data', con=engine, if_exists='append', index=False)
    time.sleep(30)

In [23]:
insert=[]
for i in range(len(gamedf)):
    insertdf=[]
    insertdf.append(gamedf.gameId[i])
    insertdf.append(gamedf.nickname[i])
    insertdf.append(gamedf.mmrAfter[i])
    insertdf.append(gamedf.matchingMode[i])
    insertdf.append(gamedf.seasonId[i])
    insertdf.append(gamedf.skinCode[i])
    insertdf.append(gamedf.characterLevel[i])
    insertdf.append(gamedf.playerKill[i])
    insertdf.append(gamedf.playerAssistant[i])
    insertdf.append(gamedf.equipment[i]['0'])
    insertdf.append(gamedf.equipment[i]['1'])
    insertdf.append(gamedf.equipment[i]['2'])
    insertdf.append(gamedf.equipment[i]['3'])
    insertdf.append(gamedf.equipment[i]['4'])
    # insertdf.append(gamedf.skillLevelInfo)
    insertdf.append(gamedf.serverName[i])
    insertdf.append(gamedf.teamNumber[i])
    insertdf.append(gamedf.victory[i])
    insertdf.append(gamedf.giveUp[i])
    insertdf.append(gamedf.killer[i])
    insertdf.append(gamedf.killerCharacter[i])
    insertdf.append(gamedf.routeIdOfStart[i])
    insert.append(insertdf)
column=['gameId','nickname','mmrAfter','matchingMode','seasonId','skinCode','characterLevel','playerKill','playerAssistant','equipment1','equipment2','equipment3','equipment4','equipment5','serverName','teamNumber','victory','giveUp','killer','killerCharacter','routeIdOfStart']
insert=pd.DataFrame(insert,columns=column)

In [ ]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM e_data"))
    
    # 조회 결과 출력
    for row in result:
        print(row)